listening-port=3478
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=cb914f8e36cee80487dfebc4563b9fb1573051af769251bbb4efd3229cb71a33
realm=videomeet.local
total-quota=100
stale-nonce=600
no-multicast-peers